name: "EDF"
description: "Get daily power consumption"
version: "1.0.1"
slug: "edf-electricity"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: null
  cron: "0 */3 * * *"
  tempocron: "0 */3 * * *"
schema:
  username: str
  cron: str
  tempocron: str
